# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MacroDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=50000)),
                ('name', models.CharField(max_length=250)),
                ('start', models.IntegerField(help_text='Character offset in file at which macro defintion starts.', null=True)),
                ('end', models.IntegerField(help_text='Character offset in file at which macro definition ends.', null=True)),
                ('line', models.IntegerField(help_text='Line number of macro definition in file.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacroRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(help_text='Character offset in source file of first character of macro call.')),
                ('line', models.IntegerField(help_text='Line number of macro call in file.', null=True)),
                ('text', models.CharField(help_text='The actual text of the macro call, with args.', max_length=4000)),
                ('macro_name', models.CharField(help_text='The ID or expression identifying the macro to be called.', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='TownNews name for this package.', max_length=250)),
                ('version', models.CharField(blank=True, help_text='Version number for the package as a whole.', max_length=20)),
                ('is_certified', models.BooleanField(help_text='Is officially certified/supported by TownNews.')),
                ('last_download', models.DateTimeField(help_text="When this package's ZIP file was downloaded.")),
                ('disk_directory', models.FilePathField(allow_files=False, allow_folders=True, blank=True, help_text="The location of the package's files on disk, relative to some common root directory.")),
                ('pkg_type', models.CharField(choices=[('g', 'global skin'), ('s', 'application skin'), ('b', 'block'), ('c', 'component')], max_length=1)),
                ('app', models.ForeignKey(help_text='The application to which this package belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='utl_files.Application')),
                ('site', models.ForeignKey(help_text="For customized packages, the site that 'owns' the customizations.", null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.TownnewsSite')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(help_text='The name of the required package', max_length=200)),
                ('dep_version', models.CharField(help_text='The specific version required.', max_length=50)),
                ('dep_pkg', models.ForeignKey(help_text='The full data on the required package (opt.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_pkg', to='utl_files.Package')),
                ('pkg', models.ForeignKey(help_text='The package which has this dependency', on_delete=django.db.models.deletion.CASCADE, to='utl_files.Package')),
            ],
            options={
                'verbose_name': 'package dependency',
                'verbose_name_plural': 'package dependencies',
            },
        ),
        migrations.CreateModel(
            name='PackageProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('pkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utl_files.Package')),
            ],
            options={
                'verbose_name': 'package property',
                'verbose_name_plural': 'package properties',
            },
        ),
        migrations.CreateModel(
            name='UTLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='utl_files')),
                ('file_path', models.FilePathField(help_text='The file path, relative to the package base directory.', max_length=2048)),
                ('pkg_directory', models.CharField(help_text='The package base directory on the hard drive.', max_length=1024)),
                ('pkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utl_files.Package')),
            ],
            options={
                'verbose_name': 'UTL File',
            },
        ),
        migrations.AddField(
            model_name='macroref',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utl_files.UTLFile'),
        ),
        migrations.AddField(
            model_name='macrodefinition',
            name='source',
            field=models.ForeignKey(help_text='The file where the macro is defined.', on_delete=django.db.models.deletion.CASCADE, to='utl_files.UTLFile'),
        ),
        migrations.AlterUniqueTogether(
            name='utlfile',
            unique_together=set([('pkg', 'file_path')]),
        ),
        migrations.AlterUniqueTogether(
            name='packageprop',
            unique_together=set([('pkg', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='packagedep',
            unique_together=set([('pkg', 'dep_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='macroref',
            unique_together=set([('source', 'start', 'macro_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='macrodefinition',
            unique_together=set([('source', 'start')]),
        ),
    ]
