# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utl_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='last_download',
            field=models.DateTimeField(help_text="When this package's ZIP file was downloaded.", null=True),
        ),
    ]
