# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-01 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utl_files', '0004_application_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='last_download',
            field=models.DateTimeField(blank=True, help_text="When this package's ZIP file was downloaded.", null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='site',
            field=models.ForeignKey(blank=True, help_text="For customized packages, the site that 'owns' the customizations.", null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.TownnewsSite'),
        ),
    ]
