# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utl_files', '0006_remove_fields_UTLFile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedep',
            name='dep_name',
            field=models.CharField(blank=True, help_text='The name of the required package', max_length=200),
        ),
        migrations.AlterField(
            model_name='packagedep',
            name='dep_pkg',
            field=models.ForeignKey(blank=True, help_text='The full data on the required package (opt.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_pkg', to='utl_files.Package'),
        ),
        migrations.AlterField(
            model_name='packagedep',
            name='dep_version',
            field=models.CharField(blank=True, help_text='The specific version required.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='packagedep',
            unique_together=set([]),
        ),
    ]
