# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_townnewssite_certified_site'),
        ('utl_files', '0007_package_dep_allow_blanks_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedUsedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utl_files.Package')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.TownnewsSite')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='certifiedusedby',
            unique_together=set([('package', 'site')]),
        ),
    ]
