# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utl_files', '0009_fix_null_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageprop',
            name='value',
            field=models.TextField(),
        ),
    ]
