# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utl_files', '0010_packageprop_change_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='utlfile',
            name='file_text',
            field=models.TextField(blank=True, help_text='Source code from UTL file.'),
        ),
    ]
