# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:02
from __future__ import unicode_literals

import datetime
from django.utils import timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_initial_data'),
        ('utl_files', '0016_add_pkg_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='disk_directory',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, help_text="The location of the package's files on disk, relative to some common root directory."),
        ),
        migrations.AddField(
            model_name='package',
            name='last_download',
            field=models.DateTimeField(default=timezone.make_aware(timezone.datetime(2016, 3, 9)),
                                       help_text="When this package's ZIP file was downloaded."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_type',
            field=models.CharField(choices=[('g', 'global skin'), ('s', 'application skin'), ('b', 'block'), ('c', 'component')], default='s', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='site',
            field=models.ForeignKey(help_text="For customized packages, the site that 'owns' the customizations.", null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.TNSite'),
        ),
        migrations.AlterField(
            model_name='package',
            name='app',
            field=models.ForeignKey(help_text='The application to which this package belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='utl_files.Application'),
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(blank=True, help_text='Version number for the package as a whole.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([]),
        ),
    ]
