# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 21:09
# pylint: disable=C0103,C0111
from __future__ import unicode_literals

from django.db import migrations

DUMMY_PAPER = ['Townnews BLOX CMS']

TOWNNEWS_SITES = [("http://townnews.com", "certified", DUMMY_PAPER[0], )]


def load_newspapers(apps, _):
    NewsPaper = apps.get_model("papers", "NewsPaper")
    for name in DUMMY_PAPER:
        new_paper = NewsPaper(name=name)
        new_paper.full_clean()
        new_paper.save()


def unload_newspapers(apps, _):
    NewsPaper = apps.get_model("papers", "NewsPaper")
    for name in DUMMY_PAPER:
        try:
            the_paper = NewsPaper.objects.get(name=name)
            the_paper.delete()
        except NewsPaper.DoesNotExist:
            pass


def load_sites(apps, _):
    TownnewsSite = apps.get_model("papers", "TownnewsSite")
    NewsPaper = apps.get_model("papers", "NewsPaper")
    for url, name, paper in TOWNNEWS_SITES:
        the_paper = NewsPaper.objects.get(name=paper)
        new_site = TownnewsSite(URL=url, name=name, paper=the_paper)
        new_site.full_clean()
        new_site.save()


def unload_sites(apps, _):
    TownnewsSite = apps.get_model("papers", "TownnewsSite")
    for url, _, _ in TOWNNEWS_SITES:
        try:
            the_site = TownnewsSite.objects.get(URL=url)
            the_site.delete()
        except TownnewsSite.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_add_help_texts_site'),
    ]

    operations = [
        migrations.operations.RunPython(load_newspapers, reverse_code=unload_newspapers),
        migrations.operations.RunPython(load_sites, reverse_code=unload_sites),
    ]
