# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_townnewssite_certified_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownnewsSiteMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(help_text='TownNews name for this package.', max_length=250)),
                ('zip_name', models.FilePathField(max_length=2000)),
                ('version', models.CharField(help_text='Version number for the package as a whole.', max_length=20)),
                ('is_certified', models.BooleanField(help_text='Is officially certified/supported by TownNews.')),
                ('last_download', models.DateTimeField(help_text="When this package's ZIP file was downloaded.")),
                ('site', models.ForeignKey(help_text='The site this metadata applies to', on_delete=django.db.models.deletion.CASCADE, to='papers.TownnewsSite')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='townnewssitemetadata',
            unique_together=set([('site', 'pkg_name', 'version', 'last_download')]),
        ),
    ]
